/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x01U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0xA0000000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B1_15 (coord B14), USER_BUTTON2 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BUTTON2_PERIPHERAL                             GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BUTTON2_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BUTTON2_CHANNEL                                  31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BUTTON2_GPIO                                   GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON2_GPIO_PIN                                 31U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BUTTON2_GPIO_PIN_MASK                    (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_USER_BUTTON2_PORT                                   GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON2_PIN                                      31U   /*!< PORT pin number */
#define BOARD_INITPINS_USER_BUTTON2_PIN_MASK                         (1U << 31U)   /*!< PORT pin mask */

/* GPIO_AD_B0_00 (coord M14), USER_BUTTON1 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BUTTON1_PERIPHERAL                             GPIO6   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BUTTON1_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BUTTON1_CHANNEL                                   0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BUTTON1_GPIO                                   GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON1_GPIO_PIN                                  0U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BUTTON1_GPIO_PIN_MASK                     (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_USER_BUTTON1_PORT                                   GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_USER_BUTTON1_PIN                                       0U   /*!< PORT pin number */
#define BOARD_INITPINS_USER_BUTTON1_PIN_MASK                          (1U << 0U)   /*!< PORT pin mask */

/* GPIO_B1_13 (coord D14), WDOG */
/* Routed pin properties */
#define BOARD_INITPINS_WDOG_PERIPHERAL                                     GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_WDOG_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_WDOG_CHANNEL                                          29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WDOG_GPIO                                           GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_WDOG_GPIO_PIN                                         29U   /*!< GPIO pin number */
#define BOARD_INITPINS_WDOG_GPIO_PIN_MASK                            (1U << 29U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_WDOG_PORT                                           GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_WDOG_PIN                                              29U   /*!< PORT pin number */
#define BOARD_INITPINS_WDOG_PIN_MASK                                 (1U << 29U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_EMC_10 (coord G1), ADDR01 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR01_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR01_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR01_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_11 (coord G3), ADDR02 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR02_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR02_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR02_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_12 (coord H1), ADDR03 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR03_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR03_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR03_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_13 (coord A6), ADDR04 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR04_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR04_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR04_CHANNEL                                       4U   /*!< Signal channel */

/* GPIO_EMC_14 (coord B6), ADDR05 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR05_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR05_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR05_CHANNEL                                       5U   /*!< Signal channel */

/* GPIO_EMC_15 (coord B1), ADDR06 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR06_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR06_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR06_CHANNEL                                       6U   /*!< Signal channel */

/* GPIO_EMC_16 (coord A5), ADDR07 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR07_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR07_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR07_CHANNEL                                       7U   /*!< Signal channel */

/* GPIO_EMC_17 (coord A4), ADDR08 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR08_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR08_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR08_CHANNEL                                       8U   /*!< Signal channel */

/* GPIO_EMC_18 (coord B2), ADDR09 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR09_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR09_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR09_CHANNEL                                       9U   /*!< Signal channel */

/* GPIO_EMC_23 (coord G2), ADDR10 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR10_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR10_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR10_CHANNEL                                      10U   /*!< Signal channel */

/* GPIO_EMC_19 (coord B4), ADDR11 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR11_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR11_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR11_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_EMC_21 (coord C1), BA0 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_BA0_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_BA0_SIGNAL                                           BA   /*!< Signal name */
#define BOARD_INIT_SDRAM_BA0_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_EMC_22 (coord F1), BA1 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_BA1_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_BA1_SIGNAL                                           BA   /*!< Signal name */
#define BOARD_INIT_SDRAM_BA1_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_EMC_24 (coord D3), CAS */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_CAS_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_CAS_SIGNAL                                     semc_cas   /*!< Signal name */

/* GPIO_EMC_27 (coord A2), CKE */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_CKE_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_CKE_SIGNAL                                     semc_cke   /*!< Signal name */

/* GPIO_EMC_26 (coord B3), CLK */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_CLK_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_CLK_SIGNAL                                     semc_clk   /*!< Signal name */

/* GPIO_EMC_25 (coord D2), RAS */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_RAS_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_RAS_SIGNAL                                     semc_ras   /*!< Signal name */

/* GPIO_EMC_28 (coord D1), WE */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_WE_PERIPHERAL                                      SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_WE_SIGNAL                                       semc_we   /*!< Signal name */

/* GPIO_EMC_29 (coord E1), CS */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_CS_PERIPHERAL                                      SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_CS_SIGNAL                                            CS   /*!< Signal name */
#define BOARD_INIT_SDRAM_CS_CHANNEL                                           0U   /*!< Signal channel */

/* GPIO_EMC_37 (coord E4), DATA15 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA15_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA15_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA15_CHANNEL                                      15U   /*!< Signal channel */

/* GPIO_EMC_36 (coord C3), DATA14 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA14_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA14_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA14_CHANNEL                                      14U   /*!< Signal channel */

/* GPIO_EMC_35 (coord E5), DATA13 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA13_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA13_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA13_CHANNEL                                      13U   /*!< Signal channel */

/* GPIO_EMC_34 (coord D4), DATA12 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA12_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA12_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA12_CHANNEL                                      12U   /*!< Signal channel */

/* GPIO_EMC_00 (coord E3), DATA00 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA00_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA00_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA00_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_01 (coord F3), DATA01 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA01_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA01_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA01_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_03 (coord G4), DATA03 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA03_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA03_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA03_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_02 (coord F4), DATA02 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA02_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA02_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA02_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_04 (coord F2), DATA04 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA04_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA04_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA04_CHANNEL                                       4U   /*!< Signal channel */

/* GPIO_EMC_05 (coord G5), DATA05 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA05_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA05_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA05_CHANNEL                                       5U   /*!< Signal channel */

/* GPIO_EMC_06 (coord H5), DATA06 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA06_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA06_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA06_CHANNEL                                       6U   /*!< Signal channel */

/* GPIO_EMC_07 (coord H4), DATA07 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA07_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA07_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA07_CHANNEL                                       7U   /*!< Signal channel */

/* GPIO_EMC_30 (coord C6), DATA08 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA08_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA08_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA08_CHANNEL                                       8U   /*!< Signal channel */

/* GPIO_EMC_31 (coord C5), DATA09 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA09_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA09_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA09_CHANNEL                                       9U   /*!< Signal channel */

/* GPIO_EMC_32 (coord D5), DATA10 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA10_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA10_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA10_CHANNEL                                      10U   /*!< Signal channel */

/* GPIO_EMC_33 (coord C4), DATA11 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DATA11_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DATA11_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INIT_SDRAM_DATA11_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_EMC_08 (coord H3), DM0 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DM0_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DM0_SIGNAL                                           DM   /*!< Signal name */
#define BOARD_INIT_SDRAM_DM0_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_EMC_38 (coord D6), DM1 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DM1_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DM1_SIGNAL                                           DM   /*!< Signal name */
#define BOARD_INIT_SDRAM_DM1_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_EMC_09 (coord C2), ADDR00 */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_ADDR00_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_ADDR00_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INIT_SDRAM_ADDR00_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_39 (coord B7), DQS */
/* Routed pin properties */
#define BOARD_INIT_SDRAM_DQS_PERIPHERAL                                     SEMC   /*!< Peripheral name */
#define BOARD_INIT_SDRAM_DQS_SIGNAL                                     semc_dqs   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_SDRAM(void);

/* GPIO_SD_B1_08 (coord P3), IO0 */
/* Routed pin properties */
#define BOARD_INIT_FLASH_IO0_PERIPHERAL                                  FLEXSPI   /*!< Peripheral name */
#define BOARD_INIT_FLASH_IO0_SIGNAL                              FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B1_09 (coord N4), IO1 */
/* Routed pin properties */
#define BOARD_INIT_FLASH_IO1_PERIPHERAL                                  FLEXSPI   /*!< Peripheral name */
#define BOARD_INIT_FLASH_IO1_SIGNAL                              FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B1_10 (coord P4), IO2 */
/* Routed pin properties */
#define BOARD_INIT_FLASH_IO2_PERIPHERAL                                  FLEXSPI   /*!< Peripheral name */
#define BOARD_INIT_FLASH_IO2_SIGNAL                              FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B1_11 (coord P5), IO3 */
/* Routed pin properties */
#define BOARD_INIT_FLASH_IO3_PERIPHERAL                                  FLEXSPI   /*!< Peripheral name */
#define BOARD_INIT_FLASH_IO3_SIGNAL                              FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_SD_B1_05 (coord N3), DQS */
/* Routed pin properties */
#define BOARD_INIT_FLASH_DQS_PERIPHERAL                                  FLEXSPI   /*!< Peripheral name */
#define BOARD_INIT_FLASH_DQS_SIGNAL                                FLEXSPI_A_DQS   /*!< Signal name */

/* GPIO_SD_B1_07 (coord L4), CLK */
/* Routed pin properties */
#define BOARD_INIT_FLASH_CLK_PERIPHERAL                                  FLEXSPI   /*!< Peripheral name */
#define BOARD_INIT_FLASH_CLK_SIGNAL                               FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B1_06 (coord L3), CS */
/* Routed pin properties */
#define BOARD_INIT_FLASH_CS_PERIPHERAL                                   FLEXSPI   /*!< Peripheral name */
#define BOARD_INIT_FLASH_CS_SIGNAL                               FLEXSPI_A_SS0_B   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_Flash(void);

#define BOARD_INIT_SD_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x04000000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INIT_SD_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x10000000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_SD_B0_04 (coord H2), DAT2 */
/* Routed pin properties */
#define BOARD_INIT_SD_DAT2_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_INIT_SD_DAT2_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_INIT_SD_DAT2_CHANNEL                                            2U   /*!< Signal channel */

/* GPIO_SD_B0_05 (coord J2), DAT3 */
/* Routed pin properties */
#define BOARD_INIT_SD_DAT3_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_INIT_SD_DAT3_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_INIT_SD_DAT3_CHANNEL                                            3U   /*!< Signal channel */

/* GPIO_SD_B0_03 (coord K1), DAT1 */
/* Routed pin properties */
#define BOARD_INIT_SD_DAT1_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_INIT_SD_DAT1_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_INIT_SD_DAT1_CHANNEL                                            1U   /*!< Signal channel */

/* GPIO_SD_B0_02 (coord J1), DAT0 */
/* Routed pin properties */
#define BOARD_INIT_SD_DAT0_PERIPHERAL                                     USDHC1   /*!< Peripheral name */
#define BOARD_INIT_SD_DAT0_SIGNAL                                     usdhc_data   /*!< Signal name */
#define BOARD_INIT_SD_DAT0_CHANNEL                                            0U   /*!< Signal channel */

/* GPIO_SD_B0_01 (coord J3), CLK */
/* Routed pin properties */
#define BOARD_INIT_SD_CLK_PERIPHERAL                                      USDHC1   /*!< Peripheral name */
#define BOARD_INIT_SD_CLK_SIGNAL                                       usdhc_clk   /*!< Signal name */

/* GPIO_SD_B0_00 (coord J4), CMD */
/* Routed pin properties */
#define BOARD_INIT_SD_CMD_PERIPHERAL                                      USDHC1   /*!< Peripheral name */
#define BOARD_INIT_SD_CMD_SIGNAL                                       usdhc_cmd   /*!< Signal name */

/* GPIO_B1_12 (coord D13), CD */
/* Routed pin properties */
#define BOARD_INIT_SD_CD_PERIPHERAL                                        GPIO2   /*!< Peripheral name */
#define BOARD_INIT_SD_CD_SIGNAL                                          gpio_io   /*!< Signal name */
#define BOARD_INIT_SD_CD_CHANNEL                                             28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_SD_CD_GPIO                                              GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_SD_CD_GPIO_PIN                                            28U   /*!< GPIO pin number */
#define BOARD_INIT_SD_CD_GPIO_PIN_MASK                               (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_INIT_SD_CD_PORT                                              GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_SD_CD_PIN                                                 28U   /*!< PORT pin number */
#define BOARD_INIT_SD_CD_PIN_MASK                                    (1U << 28U)   /*!< PORT pin mask */

/* GPIO_AD_B1_10 (coord L13), SD_PWR_EN */
/* Routed pin properties */
#define BOARD_INIT_SD_SD_PWR_EN_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INIT_SD_SD_PWR_EN_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INIT_SD_SD_PWR_EN_CHANNEL                                      26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_SD_SD_PWR_EN_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_SD_SD_PWR_EN_GPIO_PIN                                     26U   /*!< GPIO pin number */
#define BOARD_INIT_SD_SD_PWR_EN_GPIO_PIN_MASK                        (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INIT_SD_SD_PWR_EN_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INIT_SD_SD_PWR_EN_PIN                                          26U   /*!< PORT pin number */
#define BOARD_INIT_SD_SD_PWR_EN_PIN_MASK                             (1U << 26U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_SD(void);

#define BOARD_INIT_WICED_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x80000000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INIT_WICED_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x4E800000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_14 (coord H14), BT_UART_CTS */
/* Routed pin properties */
#define BOARD_INIT_WICED_BT_UART_CTS_PERIPHERAL                          LPUART1   /*!< Peripheral name */
#define BOARD_INIT_WICED_BT_UART_CTS_SIGNAL                                CTS_B   /*!< Signal name */

/* GPIO_AD_B0_15 (coord L10), BT_UART_RTS */
/* Routed pin properties */
#define BOARD_INIT_WICED_BT_UART_RTS_PERIPHERAL                          LPUART1   /*!< Peripheral name */
#define BOARD_INIT_WICED_BT_UART_RTS_SIGNAL                                RTS_B   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), BT_UART_TXD */
/* Routed pin properties */
#define BOARD_INIT_WICED_BT_UART_TXD_PERIPHERAL                          LPUART1   /*!< Peripheral name */
#define BOARD_INIT_WICED_BT_UART_TXD_SIGNAL                                   RX   /*!< Signal name */

/* GPIO_AD_B0_12 (coord K14), BT_UART_RXD */
/* Routed pin properties */
#define BOARD_INIT_WICED_BT_UART_RXD_PERIPHERAL                          LPUART1   /*!< Peripheral name */
#define BOARD_INIT_WICED_BT_UART_RXD_SIGNAL                                   TX   /*!< Signal name */

/* GPIO_B1_09 (coord A13), WL_REG_ON */
/* Routed pin properties */
#define BOARD_INIT_WICED_WL_REG_ON_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WL_REG_ON_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INIT_WICED_WL_REG_ON_CHANNEL                                   25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_WICED_WL_REG_ON_GPIO                                    GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_WICED_WL_REG_ON_GPIO_PIN                                  25U   /*!< GPIO pin number */
#define BOARD_INIT_WICED_WL_REG_ON_GPIO_PIN_MASK                     (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INIT_WICED_WL_REG_ON_PORT                                    GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_WICED_WL_REG_ON_PIN                                       25U   /*!< PORT pin number */
#define BOARD_INIT_WICED_WL_REG_ON_PIN_MASK                          (1U << 25U)   /*!< PORT pin mask */

/* GPIO_B1_10 (coord B13), BT_REG_ON */
/* Routed pin properties */
#define BOARD_INIT_WICED_BT_REG_ON_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define BOARD_INIT_WICED_BT_REG_ON_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INIT_WICED_BT_REG_ON_CHANNEL                                   26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_WICED_BT_REG_ON_GPIO                                    GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_WICED_BT_REG_ON_GPIO_PIN                                  26U   /*!< GPIO pin number */
#define BOARD_INIT_WICED_BT_REG_ON_GPIO_PIN_MASK                     (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INIT_WICED_BT_REG_ON_PORT                                    GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_WICED_BT_REG_ON_PIN                                       26U   /*!< PORT pin number */
#define BOARD_INIT_WICED_BT_REG_ON_PIN_MASK                          (1U << 26U)   /*!< PORT pin mask */

/* GPIO_B1_07 (coord B12), BT_HOSTWAKE */
/* Routed pin properties */
#define BOARD_INIT_WICED_BT_HOSTWAKE_PERIPHERAL                            GPIO2   /*!< Peripheral name */
#define BOARD_INIT_WICED_BT_HOSTWAKE_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INIT_WICED_BT_HOSTWAKE_CHANNEL                                 23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_WICED_BT_HOSTWAKE_GPIO                                  GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_WICED_BT_HOSTWAKE_GPIO_PIN                                23U   /*!< GPIO pin number */
#define BOARD_INIT_WICED_BT_HOSTWAKE_GPIO_PIN_MASK                   (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INIT_WICED_BT_HOSTWAKE_PORT                                  GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_WICED_BT_HOSTWAKE_PIN                                     23U   /*!< PORT pin number */
#define BOARD_INIT_WICED_BT_HOSTWAKE_PIN_MASK                        (1U << 23U)   /*!< PORT pin mask */

/* GPIO_B1_11 (coord C13), WIFI_GPIO2 */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIFI_GPIO2_PERIPHERAL                             GPIO2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIFI_GPIO2_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INIT_WICED_WIFI_GPIO2_CHANNEL                                  27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_WICED_WIFI_GPIO2_GPIO                                   GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_WICED_WIFI_GPIO2_GPIO_PIN                                 27U   /*!< GPIO pin number */
#define BOARD_INIT_WICED_WIFI_GPIO2_GPIO_PIN_MASK                    (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INIT_WICED_WIFI_GPIO2_PORT                                   GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_WICED_WIFI_GPIO2_PIN                                      27U   /*!< PORT pin number */
#define BOARD_INIT_WICED_WIFI_GPIO2_PIN_MASK                         (1U << 27U)   /*!< PORT pin mask */

/* GPIO_B1_14 (coord C14), WIFI_GPIO3 */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIFI_GPIO3_PERIPHERAL                             GPIO2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIFI_GPIO3_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INIT_WICED_WIFI_GPIO3_CHANNEL                                  30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_WICED_WIFI_GPIO3_GPIO                                   GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_WICED_WIFI_GPIO3_GPIO_PIN                                 30U   /*!< GPIO pin number */
#define BOARD_INIT_WICED_WIFI_GPIO3_GPIO_PIN_MASK                    (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INIT_WICED_WIFI_GPIO3_PORT                                   GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_WICED_WIFI_GPIO3_PIN                                      30U   /*!< PORT pin number */
#define BOARD_INIT_WICED_WIFI_GPIO3_PIN_MASK                         (1U << 30U)   /*!< PORT pin mask */

/* GPIO_AD_B1_15 (coord J14), BT_WAKE */
/* Routed pin properties */
#define BOARD_INIT_WICED_BT_WAKE_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INIT_WICED_BT_WAKE_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INIT_WICED_BT_WAKE_CHANNEL                                     31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_WICED_BT_WAKE_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_WICED_BT_WAKE_GPIO_PIN                                    31U   /*!< GPIO pin number */
#define BOARD_INIT_WICED_BT_WAKE_GPIO_PIN_MASK                       (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INIT_WICED_BT_WAKE_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INIT_WICED_BT_WAKE_PIN                                         31U   /*!< PORT pin number */
#define BOARD_INIT_WICED_BT_WAKE_PIN_MASK                            (1U << 31U)   /*!< PORT pin mask */

/* GPIO_AD_B1_09 (coord M13), WIFI_SDIO_CLK */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIFI_SDIO_CLK_PERIPHERAL                         USDHC2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIFI_SDIO_CLK_SIGNAL                          usdhc_clk   /*!< Signal name */

/* GPIO_AD_B1_08 (coord H13), WIFI_SDIO_CMD */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIFI_SDIO_CMD_PERIPHERAL                         USDHC2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIFI_SDIO_CMD_SIGNAL                          usdhc_cmd   /*!< Signal name */

/* GPIO_AD_B1_04 (coord L12), WIDI_SDIO_D0 */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIDI_SDIO_D0_PERIPHERAL                          USDHC2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIDI_SDIO_D0_SIGNAL                          usdhc_data   /*!< Signal name */
#define BOARD_INIT_WICED_WIDI_SDIO_D0_CHANNEL                                 0U   /*!< Signal channel */

/* GPIO_AD_B1_05 (coord K12), WIDI_SDIO_D1 */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIDI_SDIO_D1_PERIPHERAL                          USDHC2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIDI_SDIO_D1_SIGNAL                          usdhc_data   /*!< Signal name */
#define BOARD_INIT_WICED_WIDI_SDIO_D1_CHANNEL                                 1U   /*!< Signal channel */

/* GPIO_AD_B1_06 (coord J12), WIDI_SDIO_D2 */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIDI_SDIO_D2_PERIPHERAL                          USDHC2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIDI_SDIO_D2_SIGNAL                          usdhc_data   /*!< Signal name */
#define BOARD_INIT_WICED_WIDI_SDIO_D2_CHANNEL                                 2U   /*!< Signal channel */

/* GPIO_AD_B1_07 (coord K10), WIDI_SDIO_D3 */
/* Routed pin properties */
#define BOARD_INIT_WICED_WIDI_SDIO_D3_PERIPHERAL                          USDHC2   /*!< Peripheral name */
#define BOARD_INIT_WICED_WIDI_SDIO_D3_SIGNAL                          usdhc_data   /*!< Signal name */
#define BOARD_INIT_WICED_WIDI_SDIO_D3_CHANNEL                                 3U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_Wiced(void);

/* USB_OTG1_DN (coord M8), DM */
/* Routed pin properties */
#define BOARD_INIT_USB_DM_PERIPHERAL                                        USB1   /*!< Peripheral name */
#define BOARD_INIT_USB_DM_SIGNAL                                     usb_otg1_dn   /*!< Signal name */

/* USB_OTG1_DP (coord L8), DP */
/* Routed pin properties */
#define BOARD_INIT_USB_DP_PERIPHERAL                                        USB1   /*!< Peripheral name */
#define BOARD_INIT_USB_DP_SIGNAL                                     usb_otg1_dp   /*!< Signal name */

/* GPIO_AD_B0_01 (coord H10), ID */
/* Routed pin properties */
#define BOARD_INIT_USB_ID_PERIPHERAL                                        USB1   /*!< Peripheral name */
#define BOARD_INIT_USB_ID_SIGNAL                                     usb_otg1_id   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_USB(void);

#define BOARD_INIT_LED_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x0CU /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_02 (coord M11), RED */
/* Routed pin properties */
#define BOARD_INIT_LED_RED_PERIPHERAL                                      GPIO6   /*!< Peripheral name */
#define BOARD_INIT_LED_RED_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INIT_LED_RED_CHANNEL                                            2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_LED_RED_GPIO                                            GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_LED_RED_GPIO_PIN                                           2U   /*!< GPIO pin number */
#define BOARD_INIT_LED_RED_GPIO_PIN_MASK                              (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INIT_LED_RED_PORT                                            GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_INIT_LED_RED_PIN                                                2U   /*!< PORT pin number */
#define BOARD_INIT_LED_RED_PIN_MASK                                   (1U << 2U)   /*!< PORT pin mask */

/* GPIO_AD_B0_03 (coord G11), GREEN */
/* Routed pin properties */
#define BOARD_INIT_LED_GREEN_PERIPHERAL                                    GPIO6   /*!< Peripheral name */
#define BOARD_INIT_LED_GREEN_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INIT_LED_GREEN_CHANNEL                                          3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_LED_GREEN_GPIO                                          GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_LED_GREEN_GPIO_PIN                                         3U   /*!< GPIO pin number */
#define BOARD_INIT_LED_GREEN_GPIO_PIN_MASK                            (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INIT_LED_GREEN_PORT                                          GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_INIT_LED_GREEN_PIN                                              3U   /*!< PORT pin number */
#define BOARD_INIT_LED_GREEN_PIN_MASK                                 (1U << 3U)   /*!< PORT pin mask */

/* GPIO_B0_11 (coord A10), PWMG */
/* Routed pin properties */
#define BOARD_INIT_LED_PWMG_PERIPHERAL                                      PWM2   /*!< Peripheral name */
#define BOARD_INIT_LED_PWMG_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INIT_LED_PWMG_CHANNEL                                           2U   /*!< Signal channel */

/* GPIO_B0_09 (coord C9), PWMB */
/* Routed pin properties */
#define BOARD_INIT_LED_PWMB_PERIPHERAL                                      PWM2   /*!< Peripheral name */
#define BOARD_INIT_LED_PWMB_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INIT_LED_PWMB_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_B0_07 (coord A9), PWMR */
/* Routed pin properties */
#define BOARD_INIT_LED_PWMR_PERIPHERAL                                      PWM2   /*!< Peripheral name */
#define BOARD_INIT_LED_PWMR_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INIT_LED_PWMR_CHANNEL                                           0U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_LED(void);

/* GPIO_AD_B0_11 (coord G10), TRST */
/* Routed pin properties */
#define BOARD_INIT_JTAG_TRST_PERIPHERAL                                     JTAG   /*!< Peripheral name */
#define BOARD_INIT_JTAG_TRST_SIGNAL                                        TRSTB   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_JTAG(void);

#define BOARD_INIT_X4_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x0F0070U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B0_01 (coord E7), SPI_MISO */
/* Routed pin properties */
#define BOARD_INIT_X4_SPI_MISO_PERIPHERAL                                 LPSPI4   /*!< Peripheral name */
#define BOARD_INIT_X4_SPI_MISO_SIGNAL                                        SDI   /*!< Signal name */

/* GPIO_B0_03 (coord D8), SPI_SCLK */
/* Routed pin properties */
#define BOARD_INIT_X4_SPI_SCLK_PERIPHERAL                                 LPSPI4   /*!< Peripheral name */
#define BOARD_INIT_X4_SPI_SCLK_SIGNAL                                        SCK   /*!< Signal name */

/* GPIO_B0_00 (coord D7), SPI_CS */
/* Routed pin properties */
#define BOARD_INIT_X4_SPI_CS_PERIPHERAL                                   LPSPI4   /*!< Peripheral name */
#define BOARD_INIT_X4_SPI_CS_SIGNAL                                         PCS0   /*!< Signal name */

/* GPIO_B0_02 (coord E8), SPI_MOSI */
/* Routed pin properties */
#define BOARD_INIT_X4_SPI_MOSI_PERIPHERAL                                 LPSPI4   /*!< Peripheral name */
#define BOARD_INIT_X4_SPI_MOSI_SIGNAL                                        SDO   /*!< Signal name */

/* GPIO_B0_06 (coord A8), EN */
/* Routed pin properties */
#define BOARD_INIT_X4_EN_PERIPHERAL                                        GPIO7   /*!< Peripheral name */
#define BOARD_INIT_X4_EN_SIGNAL                                          gpio_io   /*!< Signal name */
#define BOARD_INIT_X4_EN_CHANNEL                                              6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_X4_EN_GPIO                                              GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_X4_EN_GPIO_PIN                                             6U   /*!< GPIO pin number */
#define BOARD_INIT_X4_EN_GPIO_PIN_MASK                                (1U << 6U)   /*!< GPIO pin mask */
#define BOARD_INIT_X4_EN_PORT                                              GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INIT_X4_EN_PIN                                                  6U   /*!< PORT pin number */
#define BOARD_INIT_X4_EN_PIN_MASK                                     (1U << 6U)   /*!< PORT pin mask */

/* GPIO_B0_04 (coord C8), GPIO1 */
/* Routed pin properties */
#define BOARD_INIT_X4_GPIO1_PERIPHERAL                                     GPIO2   /*!< Peripheral name */
#define BOARD_INIT_X4_GPIO1_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INIT_X4_GPIO1_CHANNEL                                           4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_X4_GPIO1_GPIO                                           GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_X4_GPIO1_GPIO_PIN                                          4U   /*!< GPIO pin number */
#define BOARD_INIT_X4_GPIO1_GPIO_PIN_MASK                             (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INIT_X4_GPIO1_PORT                                           GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_X4_GPIO1_PIN                                               4U   /*!< PORT pin number */
#define BOARD_INIT_X4_GPIO1_PIN_MASK                                  (1U << 4U)   /*!< PORT pin mask */

/* GPIO_B0_05 (coord B8), GPIO2 */
/* Routed pin properties */
#define BOARD_INIT_X4_GPIO2_PERIPHERAL                                     GPIO2   /*!< Peripheral name */
#define BOARD_INIT_X4_GPIO2_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INIT_X4_GPIO2_CHANNEL                                           5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_X4_GPIO2_GPIO                                           GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_X4_GPIO2_GPIO_PIN                                          5U   /*!< GPIO pin number */
#define BOARD_INIT_X4_GPIO2_GPIO_PIN_MASK                             (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INIT_X4_GPIO2_PORT                                           GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_X4_GPIO2_PIN                                               5U   /*!< PORT pin number */
#define BOARD_INIT_X4_GPIO2_PIN_MASK                                  (1U << 5U)   /*!< PORT pin mask */

/* GPIO_B1_01 (coord B11), GPIO3 */
/* Routed pin properties */
#define BOARD_INIT_X4_GPIO3_PERIPHERAL                                     GPIO2   /*!< Peripheral name */
#define BOARD_INIT_X4_GPIO3_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INIT_X4_GPIO3_CHANNEL                                          17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_X4_GPIO3_GPIO                                           GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_X4_GPIO3_GPIO_PIN                                         17U   /*!< GPIO pin number */
#define BOARD_INIT_X4_GPIO3_GPIO_PIN_MASK                            (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INIT_X4_GPIO3_PORT                                           GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_X4_GPIO3_PIN                                              17U   /*!< PORT pin number */
#define BOARD_INIT_X4_GPIO3_PIN_MASK                                 (1U << 17U)   /*!< PORT pin mask */

/* GPIO_B1_00 (coord A11), GPIO4 */
/* Routed pin properties */
#define BOARD_INIT_X4_GPIO4_PERIPHERAL                                     GPIO2   /*!< Peripheral name */
#define BOARD_INIT_X4_GPIO4_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INIT_X4_GPIO4_CHANNEL                                          16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_X4_GPIO4_GPIO                                           GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_X4_GPIO4_GPIO_PIN                                         16U   /*!< GPIO pin number */
#define BOARD_INIT_X4_GPIO4_GPIO_PIN_MASK                            (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INIT_X4_GPIO4_PORT                                           GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_X4_GPIO4_PIN                                              16U   /*!< PORT pin number */
#define BOARD_INIT_X4_GPIO4_PIN_MASK                                 (1U << 16U)   /*!< PORT pin mask */

/* GPIO_B1_02 (coord C11), SPI_CS2 */
/* Routed pin properties */
#define BOARD_INIT_X4_SPI_CS2_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INIT_X4_SPI_CS2_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INIT_X4_SPI_CS2_CHANNEL                                        18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_X4_SPI_CS2_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_X4_SPI_CS2_GPIO_PIN                                       18U   /*!< GPIO pin number */
#define BOARD_INIT_X4_SPI_CS2_GPIO_PIN_MASK                          (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INIT_X4_SPI_CS2_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_X4_SPI_CS2_PIN                                            18U   /*!< PORT pin number */
#define BOARD_INIT_X4_SPI_CS2_PIN_MASK                               (1U << 18U)   /*!< PORT pin mask */

/* GPIO_B1_03 (coord D11), SPI_CS1 */
/* Routed pin properties */
#define BOARD_INIT_X4_SPI_CS1_PERIPHERAL                                   GPIO2   /*!< Peripheral name */
#define BOARD_INIT_X4_SPI_CS1_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INIT_X4_SPI_CS1_CHANNEL                                        19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INIT_X4_SPI_CS1_GPIO                                         GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INIT_X4_SPI_CS1_GPIO_PIN                                       19U   /*!< GPIO pin number */
#define BOARD_INIT_X4_SPI_CS1_GPIO_PIN_MASK                          (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INIT_X4_SPI_CS1_PORT                                         GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INIT_X4_SPI_CS1_PIN                                            19U   /*!< PORT pin number */
#define BOARD_INIT_X4_SPI_CS1_PIN_MASK                               (1U << 19U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_X4(void);

/* GPIO_AD_B1_00 (coord J11), SCL */
/* Routed pin properties */
#define BOARD_INIT_I2C_SCL_PERIPHERAL                                     LPI2C1   /*!< Peripheral name */
#define BOARD_INIT_I2C_SCL_SIGNAL                                            SCL   /*!< Signal name */

/* GPIO_AD_B1_01 (coord K11), SDA */
/* Routed pin properties */
#define BOARD_INIT_I2C_SDA_PERIPHERAL                                     LPI2C1   /*!< Peripheral name */
#define BOARD_INIT_I2C_SDA_SIGNAL                                            SDA   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_I2C(void);

/* GPIO_AD_B1_02 (coord L11), UART2_TX */
/* Routed pin properties */
#define BOARD_INIT_UART_UART2_TX_PERIPHERAL                              LPUART2   /*!< Peripheral name */
#define BOARD_INIT_UART_UART2_TX_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B1_03 (coord M12), UART2_RX */
/* Routed pin properties */
#define BOARD_INIT_UART_UART2_RX_PERIPHERAL                              LPUART2   /*!< Peripheral name */
#define BOARD_INIT_UART_UART2_RX_SIGNAL                                       RX   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_UART(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
