/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MIMXRT1062xxxxA
package_id: MIMXRT1062DVJ6A
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: H2, pin_signal: GPIO_SD_B0_04, label: DAT2, identifier: DAT2}
- {pin_num: K1, pin_signal: GPIO_SD_B0_03, label: DAT1, identifier: DAT1}
- {pin_num: J1, pin_signal: GPIO_SD_B0_02, label: DAT0, identifier: DAT0}
- {pin_num: J2, pin_signal: GPIO_SD_B0_05, label: DAT3, identifier: DAT3}
- {pin_num: J4, pin_signal: GPIO_SD_B0_00, label: CMD, identifier: CMD}
- {pin_num: J3, pin_signal: GPIO_SD_B0_01, label: CLK, identifier: CLK}
- {pin_num: L3, pin_signal: GPIO_SD_B1_06, label: CS, identifier: CS}
- {pin_num: L4, pin_signal: GPIO_SD_B1_07, label: CLK, identifier: CLK}
- {pin_num: P3, pin_signal: GPIO_SD_B1_08, label: IO0, identifier: IO0}
- {pin_num: N4, pin_signal: GPIO_SD_B1_09, label: IO1, identifier: IO1}
- {pin_num: P4, pin_signal: GPIO_SD_B1_10, label: IO2, identifier: IO2}
- {pin_num: P5, pin_signal: GPIO_SD_B1_11, label: IO3, identifier: IO3}
- {pin_num: N3, pin_signal: GPIO_SD_B1_05, label: DQS, identifier: DQS, comment: pin not on flash chip. floating to enable 133 MHz}
- {pin_num: L5, pin_signal: GPIO_SD_B1_00, label: WIFI_SDIO_D3, identifier: WIFI_SDIO_D3}
- {pin_num: M5, pin_signal: GPIO_SD_B1_01, label: WIFI_SDIO_D2, identifier: WIFI_SDIO_D2}
- {pin_num: M3, pin_signal: GPIO_SD_B1_02, label: WIFI_SDIO_D1, identifier: WIFI_SDIO_D1}
- {pin_num: M4, pin_signal: GPIO_SD_B1_03, label: WIFI_SDIO_D0, identifier: WIFI_SDIO_D0}
- {pin_num: P2, pin_signal: GPIO_SD_B1_04, label: WIFI_SDIO_CLK, identifier: WIFI_SDIO_CLK}
- {pin_num: H13, pin_signal: GPIO_AD_B1_08, label: WIFI_SDIO_CMD, identifier: WIFI_SDIO_CMD}
- {pin_num: M11, pin_signal: GPIO_AD_B0_02, label: RED, identifier: RED}
- {pin_num: G11, pin_signal: GPIO_AD_B0_03, label: GREEN, identifier: GREEN}
- {pin_num: E14, pin_signal: GPIO_AD_B0_06, label: TMS, identifier: TMS}
- {pin_num: F12, pin_signal: GPIO_AD_B0_07, label: TCK, identifier: TCK}
- {pin_num: F13, pin_signal: GPIO_AD_B0_08, label: MOD, identifier: MOD}
- {pin_num: F14, pin_signal: GPIO_AD_B0_09, label: TDI, identifier: TDI}
- {pin_num: G13, pin_signal: GPIO_AD_B0_10, label: TDO, identifier: TDO}
- {pin_num: G10, pin_signal: GPIO_AD_B0_11, label: TRST, identifier: TRST}
- {pin_num: K14, pin_signal: GPIO_AD_B0_12, label: BT_UART_RXD, identifier: BT_UART_RXD}
- {pin_num: L14, pin_signal: GPIO_AD_B0_13, label: BT_UART_TXD, identifier: BT_UART_TXD}
- {pin_num: L10, pin_signal: GPIO_AD_B0_15, label: BT_UART_RTS, identifier: BT_UART_RTS}
- {pin_num: H14, pin_signal: GPIO_AD_B0_14, label: BT_UART_CTS, identifier: BT_UART_CTS}
- {pin_num: J11, pin_signal: GPIO_AD_B1_00, label: SCL, identifier: SCL}
- {pin_num: K11, pin_signal: GPIO_AD_B1_01, label: SDA, identifier: SDA}
- {pin_num: L11, pin_signal: GPIO_AD_B1_02, label: UART2_TX, identifier: UART2_TX}
- {pin_num: L12, pin_signal: GPIO_AD_B1_04, label: WIDI_SDIO_D0, identifier: WIDI_SDIO_D0}
- {pin_num: K12, pin_signal: GPIO_AD_B1_05, label: WIDI_SDIO_D1, identifier: WIDI_SDIO_D1}
- {pin_num: J12, pin_signal: GPIO_AD_B1_06, label: WIDI_SDIO_D2, identifier: WIDI_SDIO_D2}
- {pin_num: K10, pin_signal: GPIO_AD_B1_07, label: WIDI_SDIO_D3, identifier: WIDI_SDIO_D3}
- {pin_num: F11, pin_signal: GPIO_AD_B0_04, label: D9, identifier: D9}
- {pin_num: M13, pin_signal: GPIO_AD_B1_09, label: WIFI_SDIO_CLK, identifier: WIFI_SDIO_CLK}
- {pin_num: L13, pin_signal: GPIO_AD_B1_10, label: SD_PWR_EN, identifier: SD_PWR_EN, comment: relocated from M13 on ep0}
- {pin_num: J13, pin_signal: GPIO_AD_B1_11, label: D6, identifier: D6}
- {pin_num: H12, pin_signal: GPIO_AD_B1_12, label: SD_CD_SW, identifier: SD_CD_SW, comment: Not sure if needed. Put it there to match the evk example...}
- {pin_num: H11, pin_signal: GPIO_AD_B1_13, label: D4, identifier: D4}
- {pin_num: G12, pin_signal: GPIO_AD_B1_14, label: SENSOR_EN, identifier: SENSOR_EN}
- {pin_num: J14, pin_signal: GPIO_AD_B1_15, label: BT_WAKE, identifier: BT_WAKE}
- {pin_num: C8, pin_signal: GPIO_B0_04, label: GPIO1, identifier: GPIO1}
- {pin_num: B8, pin_signal: GPIO_B0_05, label: GPIO2, identifier: GPIO2}
- {pin_num: A8, pin_signal: GPIO_B0_06, label: EN, identifier: EN}
- {pin_num: E7, pin_signal: GPIO_B0_01, label: SPI_MISO, identifier: SPI_MISO}
- {pin_num: D8, pin_signal: GPIO_B0_03, label: SPI_SCLK, identifier: SPI_SCLK}
- {pin_num: D7, pin_signal: GPIO_B0_00, label: SPI_CS, identifier: SPI_CS}
- {pin_num: E8, pin_signal: GPIO_B0_02, label: SPI_MOSI, identifier: SPI_MOSI}
- {pin_num: A9, pin_signal: GPIO_B0_07, label: PWMR, identifier: PWMR}
- {pin_num: C9, pin_signal: GPIO_B0_09, label: PWMB, identifier: PWMB}
- {pin_num: A10, pin_signal: GPIO_B0_11, label: PWMG, identifier: PWMG}
- {pin_num: B14, pin_signal: GPIO_B1_15, label: USER_BUTTON2, identifier: FACRESET_BUTTON;USER_BUTTON2}
- {pin_num: D10, pin_signal: GPIO_B0_13, label: MCKI, identifier: MCKI}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: GPIO4, identifier: SDTO;GPIO4}
- {pin_num: B11, pin_signal: GPIO_B1_01, label: GPIO3, identifier: SDTI;GPIO3}
- {pin_num: C11, pin_signal: GPIO_B1_02, label: SPI_CS2, identifier: BICK;SPI_CS2}
- {pin_num: D11, pin_signal: GPIO_B1_03, label: SPI_CS1, identifier: FCK;SPI_CS1}
- {pin_num: E12, pin_signal: GPIO_B1_04, label: HTS221_DRDY, identifier: HTS221_DRDY}
- {pin_num: D12, pin_signal: GPIO_B1_05, label: PDN, identifier: PDN}
- {pin_num: C12, pin_signal: GPIO_B1_06, label: WL_SDIO_HOSTWAKE, identifier: WL_SDIO_HOSTWAKE}
- {pin_num: B12, pin_signal: GPIO_B1_07, label: BT_HOSTWAKE, identifier: BT_HOSTWAKE}
- {pin_num: A12, pin_signal: GPIO_B1_08, label: ALS_INT, identifier: ALS_INT}
- {pin_num: A13, pin_signal: GPIO_B1_09, label: WL_REG_ON, identifier: WL_REG_ON}
- {pin_num: B13, pin_signal: GPIO_B1_10, label: BT_REG_ON, identifier: BT_REG_ON}
- {pin_num: C13, pin_signal: GPIO_B1_11, label: WIFI_GPIO2, identifier: WIFI_GPIO2}
- {pin_num: D13, pin_signal: GPIO_B1_12, label: CD, identifier: CD}
- {pin_num: C14, pin_signal: GPIO_B1_14, label: WIFI_GPIO3, identifier: WIFI_GPIO3}
- {pin_num: D14, pin_signal: GPIO_B1_13, label: WDOG, identifier: WDOG}
- {pin_num: E3, pin_signal: GPIO_EMC_00, label: DATA00, identifier: DATA00}
- {pin_num: F3, pin_signal: GPIO_EMC_01, label: DATA01, identifier: DATA01}
- {pin_num: F4, pin_signal: GPIO_EMC_02, label: DATA02, identifier: DATA02}
- {pin_num: G4, pin_signal: GPIO_EMC_03, label: DATA03, identifier: DATA03}
- {pin_num: F2, pin_signal: GPIO_EMC_04, label: DATA04, identifier: DATA04}
- {pin_num: G5, pin_signal: GPIO_EMC_05, label: DATA05, identifier: DATA05}
- {pin_num: H5, pin_signal: GPIO_EMC_06, label: DATA06, identifier: DATA06}
- {pin_num: H4, pin_signal: GPIO_EMC_07, label: DATA07, identifier: DATA07}
- {pin_num: C6, pin_signal: GPIO_EMC_30, label: DATA08, identifier: DATA08}
- {pin_num: C5, pin_signal: GPIO_EMC_31, label: DATA09, identifier: DATA09}
- {pin_num: D5, pin_signal: GPIO_EMC_32, label: DATA10, identifier: DATA10}
- {pin_num: C4, pin_signal: GPIO_EMC_33, label: DATA11, identifier: DATA11}
- {pin_num: D4, pin_signal: GPIO_EMC_34, label: DATA12, identifier: DATA12}
- {pin_num: E5, pin_signal: GPIO_EMC_35, label: DATA13, identifier: DATA13}
- {pin_num: C3, pin_signal: GPIO_EMC_36, label: DATA14, identifier: DATA14}
- {pin_num: E4, pin_signal: GPIO_EMC_37, label: DATA15, identifier: DATA15}
- {pin_num: C2, pin_signal: GPIO_EMC_09, label: ADDR00, identifier: ADDR00}
- {pin_num: G1, pin_signal: GPIO_EMC_10, label: ADDR01, identifier: ADDR01}
- {pin_num: G3, pin_signal: GPIO_EMC_11, label: ADDR02, identifier: ADDR02}
- {pin_num: H1, pin_signal: GPIO_EMC_12, label: ADDR03, identifier: ADDR03}
- {pin_num: A6, pin_signal: GPIO_EMC_13, label: ADDR04, identifier: ADDR04}
- {pin_num: B6, pin_signal: GPIO_EMC_14, label: ADDR05, identifier: ADDR05}
- {pin_num: B1, pin_signal: GPIO_EMC_15, label: ADDR06, identifier: ADDR06}
- {pin_num: A5, pin_signal: GPIO_EMC_16, label: ADDR07, identifier: ADDR07}
- {pin_num: A4, pin_signal: GPIO_EMC_17, label: ADDR08, identifier: ADDR08}
- {pin_num: B2, pin_signal: GPIO_EMC_18, label: ADDR09, identifier: ADDR09}
- {pin_num: G2, pin_signal: GPIO_EMC_23, label: ADDR10, identifier: ADDR10}
- {pin_num: B4, pin_signal: GPIO_EMC_19, label: ADDR11, identifier: ADDR11}
- {pin_num: C1, pin_signal: GPIO_EMC_21, label: BA0, identifier: BA0}
- {pin_num: F1, pin_signal: GPIO_EMC_22, label: BA1, identifier: BA1}
- {pin_num: D3, pin_signal: GPIO_EMC_24, label: CAS, identifier: CAS}
- {pin_num: D2, pin_signal: GPIO_EMC_25, label: RAS, identifier: RAS}
- {pin_num: B3, pin_signal: GPIO_EMC_26, label: CLK, identifier: CLK}
- {pin_num: A2, pin_signal: GPIO_EMC_27, label: CKE, identifier: CKE}
- {pin_num: E1, pin_signal: GPIO_EMC_29, label: CS, identifier: CS}
- {pin_num: D1, pin_signal: GPIO_EMC_28, label: WE, identifier: WE}
- {pin_num: D6, pin_signal: GPIO_EMC_38, label: DM1, identifier: DM1}
- {pin_num: H3, pin_signal: GPIO_EMC_08, label: DM0, identifier: DM0}
- {pin_num: M12, pin_signal: GPIO_AD_B1_03, label: UART2_RX, identifier: UART2_RX}
- {pin_num: H10, pin_signal: GPIO_AD_B0_01, label: ID, identifier: ID}
- {pin_num: M8, pin_signal: USB_OTG1_DN, label: DM, identifier: DM}
- {pin_num: L8, pin_signal: USB_OTG1_DP, label: DP, identifier: DP}
- {pin_num: M14, pin_signal: GPIO_AD_B0_00, label: USER_BUTTON1, identifier: SLEEPAIR_BUTTON;USER_BUTTON1}
- {pin_num: B7, pin_signal: GPIO_EMC_39, label: DQS, identifier: DQS}
- {pin_num: C7, pin_signal: GPIO_EMC_41, label: VSELECT, identifier: VSELECT}
power_domains: {DCDC_IN: '3.3', DCDC_IN_Q: '3.3', DCDC_LP: '1.15', DCDC_PSWITCH: '3.3', DCDC_SENSE: '1.15', NVCC_EMC: '3.3', NVCC_GPIO: '3.3', NVCC_PLL: '1.1', NVCC_SD0: '3.3',
  NVCC_SD1: '3.3', VDDA_ADC_3P3: '3.3', VDD_HIGH_CAP: '2.5', VDD_HIGH_IN: '3.3', VDD_SNVS_CAP: '3.3', VDD_SNVS_IN: '3.3', VDD_SOC_IN: '1.15', VDD_USB_CAP: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
    BOARD_Init_SD();
    BOARD_Init_Wiced();
    BOARD_Init_LED();
    BOARD_Init_X4();
    BOARD_Init_I2C();
    BOARD_Init_UART();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B14, peripheral: GPIO7, signal: 'gpio_io, 31', pin_signal: GPIO_B1_15, identifier: USER_BUTTON2, direction: INPUT, gpio_interrupt: kGPIO_IntRisingOrFallingEdge,
    hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm, pull_keeper_select: Pull, drive_strength: R0_4}
  - {pin_num: M14, peripheral: GPIO6, signal: 'gpio_io, 00', pin_signal: GPIO_AD_B0_00, identifier: USER_BUTTON1, direction: INPUT, gpio_interrupt: kGPIO_IntRisingOrFallingEdge,
    hysteresis_enable: Enable, pull_up_down_config: Pull_Up_100K_Ohm, pull_keeper_select: Pull, drive_strength: R0_4}
  - {pin_num: D14, peripheral: GPIO2, signal: 'gpio_io, 29', pin_signal: GPIO_B1_13}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of USER_BUTTON1 on GPIO_AD_B0_00 (pin M14) */
  gpio_pin_config_t USER_BUTTON1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingOrFallingEdge
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_00 (pin M14) */
  GPIO_PinInit(GPIO6, 0U, &USER_BUTTON1_config);
  /* Enable GPIO pin interrupt on GPIO_AD_B0_00 (pin M14) */
  GPIO_PortEnableInterrupts(GPIO6, 1U << 0U);

  /* GPIO configuration of USER_BUTTON2 on GPIO_B1_15 (pin B14) */
  gpio_pin_config_t USER_BUTTON2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingOrFallingEdge
  };
  /* Initialize GPIO functionality on GPIO_B1_15 (pin B14) */
  GPIO_PinInit(GPIO7, 31U, &USER_BUTTON2_config);
  /* Enable GPIO pin interrupt on GPIO_B1_15 (pin B14) */
  GPIO_PortEnableInterrupts(GPIO7, 1U << 31U);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_00_GPIO1_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_13_GPIO2_IO29, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_15_GPIO2_IO31, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x01U) 
    );
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x80000000U) 
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_00_GPIO1_IO00, 0x01B0A0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_15_GPIO2_IO31, 0x01B0A0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_SDRAM:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: G1, peripheral: SEMC, signal: 'ADDR, 01', pin_signal: GPIO_EMC_10, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: G3, peripheral: SEMC, signal: 'ADDR, 02', pin_signal: GPIO_EMC_11, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: H1, peripheral: SEMC, signal: 'ADDR, 03', pin_signal: GPIO_EMC_12, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: A6, peripheral: SEMC, signal: 'ADDR, 04', pin_signal: GPIO_EMC_13, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: B6, peripheral: SEMC, signal: 'ADDR, 05', pin_signal: GPIO_EMC_14, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: B1, peripheral: SEMC, signal: 'ADDR, 06', pin_signal: GPIO_EMC_15, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: A5, peripheral: SEMC, signal: 'ADDR, 07', pin_signal: GPIO_EMC_16, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: A4, peripheral: SEMC, signal: 'ADDR, 08', pin_signal: GPIO_EMC_17, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: B2, peripheral: SEMC, signal: 'ADDR, 09', pin_signal: GPIO_EMC_18, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: G2, peripheral: SEMC, signal: 'ADDR, 10', pin_signal: GPIO_EMC_23, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: B4, peripheral: SEMC, signal: 'ADDR, 11', pin_signal: GPIO_EMC_19, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: C1, peripheral: SEMC, signal: 'BA, 0', pin_signal: GPIO_EMC_21, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: F1, peripheral: SEMC, signal: 'BA, 1', pin_signal: GPIO_EMC_22, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: D3, peripheral: SEMC, signal: semc_cas, pin_signal: GPIO_EMC_24, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: A2, peripheral: SEMC, signal: semc_cke, pin_signal: GPIO_EMC_27, hysteresis_enable: Enable, pull_keeper_select: Keeper, speed: MHZ_200, drive_strength: R0_7,
    slew_rate: Fast}
  - {pin_num: B3, peripheral: SEMC, signal: semc_clk, pin_signal: GPIO_EMC_26, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: D2, peripheral: SEMC, signal: semc_ras, pin_signal: GPIO_EMC_25, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: D1, peripheral: SEMC, signal: semc_we, pin_signal: GPIO_EMC_28, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: E1, peripheral: SEMC, signal: 'CS, 0', pin_signal: GPIO_EMC_29, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: E4, peripheral: SEMC, signal: 'DATA, 15', pin_signal: GPIO_EMC_37, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: C3, peripheral: SEMC, signal: 'DATA, 14', pin_signal: GPIO_EMC_36, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: E5, peripheral: SEMC, signal: 'DATA, 13', pin_signal: GPIO_EMC_35, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: D4, peripheral: SEMC, signal: 'DATA, 12', pin_signal: GPIO_EMC_34, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: E3, peripheral: SEMC, signal: 'DATA, 00', pin_signal: GPIO_EMC_00, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: F3, peripheral: SEMC, signal: 'DATA, 01', pin_signal: GPIO_EMC_01, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: G4, peripheral: SEMC, signal: 'DATA, 03', pin_signal: GPIO_EMC_03, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: F4, peripheral: SEMC, signal: 'DATA, 02', pin_signal: GPIO_EMC_02, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: F2, peripheral: SEMC, signal: 'DATA, 04', pin_signal: GPIO_EMC_04, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: G5, peripheral: SEMC, signal: 'DATA, 05', pin_signal: GPIO_EMC_05, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: H5, peripheral: SEMC, signal: 'DATA, 06', pin_signal: GPIO_EMC_06, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: H4, peripheral: SEMC, signal: 'DATA, 07', pin_signal: GPIO_EMC_07, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: C6, peripheral: SEMC, signal: 'DATA, 08', pin_signal: GPIO_EMC_30, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: C5, peripheral: SEMC, signal: 'DATA, 09', pin_signal: GPIO_EMC_31, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: D5, peripheral: SEMC, signal: 'DATA, 10', pin_signal: GPIO_EMC_32, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: C4, peripheral: SEMC, signal: 'DATA, 11', pin_signal: GPIO_EMC_33, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: H3, peripheral: SEMC, signal: 'DM, 0', pin_signal: GPIO_EMC_08, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: D6, peripheral: SEMC, signal: 'DM, 1', pin_signal: GPIO_EMC_38, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: C2, peripheral: SEMC, signal: 'ADDR, 00', pin_signal: GPIO_EMC_09, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: B7, peripheral: SEMC, signal: semc_dqs, pin_signal: GPIO_EMC_39, hysteresis_enable: Enable, speed: MHZ_200, drive_strength: R0_7, slew_rate: Fast}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_SDRAM
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_SDRAM(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_00_SEMC_DATA00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_01_SEMC_DATA01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_02_SEMC_DATA02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_03_SEMC_DATA03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_04_SEMC_DATA04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_05_SEMC_DATA05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_06_SEMC_DATA06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_07_SEMC_DATA07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_08_SEMC_DM00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_09_SEMC_ADDR00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_10_SEMC_ADDR01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_11_SEMC_ADDR02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_12_SEMC_ADDR03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_13_SEMC_ADDR04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_14_SEMC_ADDR05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_15_SEMC_ADDR06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_16_SEMC_ADDR07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_17_SEMC_ADDR08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_18_SEMC_ADDR09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_19_SEMC_ADDR11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_21_SEMC_BA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_22_SEMC_BA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_23_SEMC_ADDR10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_24_SEMC_CAS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_25_SEMC_RAS, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_26_SEMC_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_27_SEMC_CKE, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_28_SEMC_WE, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_29_SEMC_CS0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_30_SEMC_DATA08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_31_SEMC_DATA09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_32_SEMC_DATA10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_33_SEMC_DATA11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_34_SEMC_DATA12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_35_SEMC_DATA13, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_36_SEMC_DATA14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_37_SEMC_DATA15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_38_SEMC_DM01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_39_SEMC_DQS, 0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_00_SEMC_DATA00, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_01_SEMC_DATA01, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_02_SEMC_DATA02, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_03_SEMC_DATA03, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_04_SEMC_DATA04, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_05_SEMC_DATA05, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_06_SEMC_DATA06, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_07_SEMC_DATA07, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_08_SEMC_DM00, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_09_SEMC_ADDR00, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_10_SEMC_ADDR01, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_11_SEMC_ADDR02, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_12_SEMC_ADDR03, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_13_SEMC_ADDR04, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_14_SEMC_ADDR05, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_15_SEMC_ADDR06, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_16_SEMC_ADDR07, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_17_SEMC_ADDR08, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_18_SEMC_ADDR09, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_19_SEMC_ADDR11, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_21_SEMC_BA0, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_22_SEMC_BA1, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_23_SEMC_ADDR10, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_24_SEMC_CAS, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_25_SEMC_RAS, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_26_SEMC_CLK, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_27_SEMC_CKE, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_28_SEMC_WE, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_29_SEMC_CS0, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_30_SEMC_DATA08, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_31_SEMC_DATA09, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_32_SEMC_DATA10, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_33_SEMC_DATA11, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_34_SEMC_DATA12, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_35_SEMC_DATA13, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_36_SEMC_DATA14, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_37_SEMC_DATA15, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_38_SEMC_DM01, 0x0110F9U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_39_SEMC_DQS, 0x0110F9U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_Flash:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: P3, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_SD_B1_08, software_input_on: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: N4, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_SD_B1_09, software_input_on: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: P4, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_SD_B1_10, software_input_on: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: P5, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_SD_B1_11, software_input_on: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: N3, peripheral: FLEXSPI, signal: FLEXSPI_A_DQS, pin_signal: GPIO_SD_B1_05, software_input_on: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: L4, peripheral: FLEXSPI, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_SD_B1_07, software_input_on: Enable, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: L3, peripheral: FLEXSPI, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_SD_B1_06, software_input_on: Enable, speed: MHZ_200, slew_rate: Fast}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_Flash
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_Flash(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_05_FLEXSPIA_DQS, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_06_FLEXSPIA_SS0_B, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_07_FLEXSPIA_SCLK, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_08_FLEXSPIA_DATA00, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_09_FLEXSPIA_DATA01, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_10_FLEXSPIA_DATA02, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_11_FLEXSPIA_DATA03, 1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_05_FLEXSPIA_DQS, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_06_FLEXSPIA_SS0_B, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_07_FLEXSPIA_SCLK, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_08_FLEXSPIA_DATA00, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_09_FLEXSPIA_DATA01, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_10_FLEXSPIA_DATA02, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_11_FLEXSPIA_DATA03, 0x10F1U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_SD:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: H2, peripheral: USDHC1, signal: 'usdhc_data, 2', pin_signal: GPIO_SD_B0_04}
  - {pin_num: J2, peripheral: USDHC1, signal: 'usdhc_data, 3', pin_signal: GPIO_SD_B0_05}
  - {pin_num: K1, peripheral: USDHC1, signal: 'usdhc_data, 1', pin_signal: GPIO_SD_B0_03}
  - {pin_num: J1, peripheral: USDHC1, signal: 'usdhc_data, 0', pin_signal: GPIO_SD_B0_02}
  - {pin_num: J3, peripheral: USDHC1, signal: usdhc_clk, pin_signal: GPIO_SD_B0_01}
  - {pin_num: J4, peripheral: USDHC1, signal: usdhc_cmd, pin_signal: GPIO_SD_B0_00}
  - {pin_num: D13, peripheral: GPIO2, signal: 'gpio_io, 28', pin_signal: GPIO_B1_12, direction: INPUT}
  - {pin_num: L13, peripheral: GPIO1, signal: 'gpio_io, 26', pin_signal: GPIO_AD_B1_10, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_SD
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_SD(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of SD_PWR_EN on GPIO_AD_B1_10 (pin L13) */
  gpio_pin_config_t SD_PWR_EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_10 (pin L13) */
  GPIO_PinInit(GPIO1, 26U, &SD_PWR_EN_config);

  /* GPIO configuration of CD on GPIO_B1_12 (pin D13) */
  gpio_pin_config_t CD_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_12 (pin D13) */
  GPIO_PinInit(GPIO2, 28U, &CD_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_GPIO1_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_12_GPIO2_IO28, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_00_USDHC1_CMD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_01_USDHC1_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_02_USDHC1_DATA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_USDHC1_DATA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_04_USDHC1_DATA2, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_05_USDHC1_DATA3, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INIT_SD_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INIT_SD_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x00U) 
    );
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_Wiced:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: H14, peripheral: LPUART1, signal: CTS_B, pin_signal: GPIO_AD_B0_14}
  - {pin_num: L10, peripheral: LPUART1, signal: RTS_B, pin_signal: GPIO_AD_B0_15}
  - {pin_num: L14, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13}
  - {pin_num: K14, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12}
  - {pin_num: A13, peripheral: GPIO2, signal: 'gpio_io, 25', pin_signal: GPIO_B1_09, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: B13, peripheral: GPIO2, signal: 'gpio_io, 26', pin_signal: GPIO_B1_10, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: B12, peripheral: GPIO2, signal: 'gpio_io, 23', pin_signal: GPIO_B1_07, direction: INPUT, pull_up_down_config: Pull_Up_100K_Ohm}
  - {pin_num: C13, peripheral: GPIO2, signal: 'gpio_io, 27', pin_signal: GPIO_B1_11}
  - {pin_num: C14, peripheral: GPIO2, signal: 'gpio_io, 30', pin_signal: GPIO_B1_14}
  - {pin_num: J14, peripheral: GPIO1, signal: 'gpio_io, 31', pin_signal: GPIO_AD_B1_15, direction: OUTPUT}
  - {pin_num: M13, peripheral: USDHC2, signal: usdhc_clk, pin_signal: GPIO_AD_B1_09, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, speed: MHZ_100, drive_strength: R0_6, slew_rate: Fast}
  - {pin_num: H13, peripheral: USDHC2, signal: usdhc_cmd, pin_signal: GPIO_AD_B1_08, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, speed: MHZ_100, drive_strength: R0_6, slew_rate: Fast}
  - {pin_num: L12, peripheral: USDHC2, signal: 'usdhc_data, 0', pin_signal: GPIO_AD_B1_04, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, speed: MHZ_100, drive_strength: R0_6, slew_rate: Fast}
  - {pin_num: K12, peripheral: USDHC2, signal: 'usdhc_data, 1', pin_signal: GPIO_AD_B1_05, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, speed: MHZ_100, drive_strength: R0_6, slew_rate: Fast}
  - {pin_num: J12, peripheral: USDHC2, signal: 'usdhc_data, 2', pin_signal: GPIO_AD_B1_06, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, speed: MHZ_100, drive_strength: R0_6, slew_rate: Fast}
  - {pin_num: K10, peripheral: USDHC2, signal: 'usdhc_data, 3', pin_signal: GPIO_AD_B1_07, software_input_on: Disable, hysteresis_enable: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, speed: MHZ_100, drive_strength: R0_6, slew_rate: Fast}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_Wiced
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_Wiced(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of BT_WAKE on GPIO_AD_B1_15 (pin J14) */
  gpio_pin_config_t BT_WAKE_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_15 (pin J14) */
  GPIO_PinInit(GPIO1, 31U, &BT_WAKE_config);

  /* GPIO configuration of BT_HOSTWAKE on GPIO_B1_07 (pin B12) */
  gpio_pin_config_t BT_HOSTWAKE_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_07 (pin B12) */
  GPIO_PinInit(GPIO2, 23U, &BT_HOSTWAKE_config);

  /* GPIO configuration of WL_REG_ON on GPIO_B1_09 (pin A13) */
  gpio_pin_config_t WL_REG_ON_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_09 (pin A13) */
  GPIO_PinInit(GPIO2, 25U, &WL_REG_ON_config);

  /* GPIO configuration of BT_REG_ON on GPIO_B1_10 (pin B13) */
  gpio_pin_config_t BT_REG_ON_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_10 (pin B13) */
  GPIO_PinInit(GPIO2, 26U, &BT_REG_ON_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_14_LPUART1_CTS_B, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_15_LPUART1_RTS_B, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_04_USDHC2_DATA0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_05_USDHC2_DATA1, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_USDHC2_DATA2, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_USDHC2_DATA3, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_USDHC2_CMD, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_09_USDHC2_CLK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_15_GPIO1_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_07_GPIO2_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_09_GPIO2_IO25, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_10_GPIO2_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_11_GPIO2_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_14_GPIO2_IO30, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INIT_WICED_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INIT_WICED_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x00U) 
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_04_USDHC2_DATA0, 0x01F0B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_05_USDHC2_DATA1, 0x01F0B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_06_USDHC2_DATA2, 0x01F0B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_07_USDHC2_DATA3, 0x01F0B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_08_USDHC2_CMD, 0x01F0B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_09_USDHC2_CLK, 0x01F0B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_07_GPIO2_IO23, 0x90B0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_USB:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: M8, peripheral: USB1, signal: usb_otg1_dn, pin_signal: USB_OTG1_DN}
  - {pin_num: L8, peripheral: USB1, signal: usb_otg1_dp, pin_signal: USB_OTG1_DP}
  - {pin_num: H10, peripheral: USB1, signal: usb_otg1_id, pin_signal: GPIO_AD_B0_01}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_USB
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_USB(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_01_USB_OTG1_ID, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_LED:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: M11, peripheral: GPIO6, signal: 'gpio_io, 02', pin_signal: GPIO_AD_B0_02, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: G11, peripheral: GPIO6, signal: 'gpio_io, 03', pin_signal: GPIO_AD_B0_03, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: A10, peripheral: PWM2, signal: 'B, 2', pin_signal: GPIO_B0_11}
  - {pin_num: C9, peripheral: PWM2, signal: 'B, 1', pin_signal: GPIO_B0_09}
  - {pin_num: A9, peripheral: PWM2, signal: 'B, 0', pin_signal: GPIO_B0_07}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_LED
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_LED(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of RED on GPIO_AD_B0_02 (pin M11) */
  gpio_pin_config_t RED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_02 (pin M11) */
  GPIO_PinInit(GPIO6, 2U, &RED_config);

  /* GPIO configuration of GREEN on GPIO_AD_B0_03 (pin G11) */
  gpio_pin_config_t GREEN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_03 (pin G11) */
  GPIO_PinInit(GPIO6, 3U, &GREEN_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_07_FLEXPWM2_PWMB00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_09_FLEXPWM2_PWMB01, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_11_FLEXPWM2_PWMB02, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INIT_LED_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x0CU) 
    );
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_JTAG:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: G10, peripheral: JTAG, signal: TRSTB, pin_signal: GPIO_AD_B0_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_JTAG
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_JTAG(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_11_JTAG_TRSTB, 0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_X4:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: E7, peripheral: LPSPI4, signal: SDI, pin_signal: GPIO_B0_01}
  - {pin_num: D8, peripheral: LPSPI4, signal: SCK, pin_signal: GPIO_B0_03}
  - {pin_num: D7, peripheral: LPSPI4, signal: PCS0, pin_signal: GPIO_B0_00}
  - {pin_num: E8, peripheral: LPSPI4, signal: SDO, pin_signal: GPIO_B0_02}
  - {pin_num: A8, peripheral: GPIO7, signal: 'gpio_io, 06', pin_signal: GPIO_B0_06, direction: OUTPUT}
  - {pin_num: C8, peripheral: GPIO2, signal: 'gpio_io, 04', pin_signal: GPIO_B0_04, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: B8, peripheral: GPIO2, signal: 'gpio_io, 05', pin_signal: GPIO_B0_05, direction: INPUT}
  - {pin_num: B11, peripheral: GPIO2, signal: 'gpio_io, 17', pin_signal: GPIO_B1_01, identifier: GPIO3, direction: INPUT}
  - {pin_num: A11, peripheral: GPIO2, signal: 'gpio_io, 16', pin_signal: GPIO_B1_00, identifier: GPIO4, direction: INPUT}
  - {pin_num: C11, peripheral: GPIO2, signal: 'gpio_io, 18', pin_signal: GPIO_B1_02, identifier: SPI_CS2, direction: INPUT}
  - {pin_num: D11, peripheral: GPIO2, signal: 'gpio_io, 19', pin_signal: GPIO_B1_03, identifier: SPI_CS1, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_X4
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_X4(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of GPIO1 on GPIO_B0_04 (pin C8) */
  gpio_pin_config_t GPIO1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_B0_04 (pin C8) */
  GPIO_PinInit(GPIO2, 4U, &GPIO1_config);
  /* Enable GPIO pin interrupt on GPIO_B0_04 (pin C8) */
  GPIO_PortEnableInterrupts(GPIO2, 1U << 4U);

  /* GPIO configuration of GPIO2 on GPIO_B0_05 (pin B8) */
  gpio_pin_config_t GPIO2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_05 (pin B8) */
  GPIO_PinInit(GPIO2, 5U, &GPIO2_config);

  /* GPIO configuration of GPIO4 on GPIO_B1_00 (pin A11) */
  gpio_pin_config_t GPIO4_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_00 (pin A11) */
  GPIO_PinInit(GPIO2, 16U, &GPIO4_config);

  /* GPIO configuration of GPIO3 on GPIO_B1_01 (pin B11) */
  gpio_pin_config_t GPIO3_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_01 (pin B11) */
  GPIO_PinInit(GPIO2, 17U, &GPIO3_config);

  /* GPIO configuration of SPI_CS2 on GPIO_B1_02 (pin C11) */
  gpio_pin_config_t SPI_CS2_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_02 (pin C11) */
  GPIO_PinInit(GPIO2, 18U, &SPI_CS2_config);

  /* GPIO configuration of SPI_CS1 on GPIO_B1_03 (pin D11) */
  gpio_pin_config_t SPI_CS1_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_03 (pin D11) */
  GPIO_PinInit(GPIO2, 19U, &SPI_CS1_config);

  /* GPIO configuration of EN on GPIO_B0_06 (pin A8) */
  gpio_pin_config_t EN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_06 (pin A8) */
  GPIO_PinInit(GPIO7, 6U, &EN_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_00_LPSPI4_PCS0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_01_LPSPI4_SDI, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_02_LPSPI4_SDO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_03_LPSPI4_SCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_04_GPIO2_IO04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_05_GPIO2_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_06_GPIO2_IO06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_00_GPIO2_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_01_GPIO2_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_02_GPIO2_IO18, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_03_GPIO2_IO19, 0U); 
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INIT_X4_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x40U) 
    );
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_I2C:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: J11, peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_AD_B1_00, software_input_on: Enable, pull_up_down_config: Pull_Up_22K_Ohm, open_drain: Enable}
  - {pin_num: K11, peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_AD_B1_01, software_input_on: Enable, pull_up_down_config: Pull_Up_22K_Ohm, open_drain: Enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_I2C
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_I2C(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_00_LPI2C1_SCL, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_01_LPI2C1_SDA, 1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_00_LPI2C1_SCL, 0xD8B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_01_LPI2C1_SDA, 0xD8B0U); 
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_Init_UART:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: L11, peripheral: LPUART2, signal: TX, pin_signal: GPIO_AD_B1_02}
  - {pin_num: M12, peripheral: LPUART2, signal: RX, pin_signal: GPIO_AD_B1_03}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_Init_UART
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_Init_UART(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_LPUART2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_LPUART2_RX, 0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
